### ISSUE TITLE
[FE] 유리 내부 컴포넌트 흐림 문제

### ISSUE THREAD

**Issue by kcwww** [boostcampwm2023/web11-SSOCK#17]
## 💦 이슈 설명
유리 재질로 만든 컴포넌트 외부 시야에서 유리 내부 시야를 바라볼때 내부에 있는 컴포넌트들이 뿌옇게 보이는 문제

- 유리 밖

![스크린샷 2023-11-09 000515](https://github.com/boostcampwm2023/web11-SSOCK/assets/98443541/8c8989c6-8983-4a87-9524-f04348ff5903)

- 유리 안

![스크린샷 2023-11-09 000526](https://github.com/boostcampwm2023/web11-SSOCK/assets/98443541/5f7ed179-56a0-43d8-babd-e462553ed146)

## ❗ 문제 해결
- [ ] 유리 내부 객체 내부 외부 구분없이 선명하게 렌더링 구현

**Comment by 5nxtnxtnxt** [comment]
유리 두께 없애고 유리 재질 바꿔서 어느정도 해결됨
다음 commit에서 확인해보고 이슈 닫읍시다~
