### ISSUE TITLE
[FE] 3D 모델 클릭 이벤트 버그

### ISSUE THREAD

**Issue by kcwww** [boostcampwm2023/web11-SSOCK#20]
## 💦 이슈 설명
3D 모델에 onClick 이벤트를 넣어서 클릭해보았는데, 유리 내부에 있는 컴포넌트 함수가 여러번 실행되는 오류 확인

![스크린샷 2023-11-09 234133](https://github.com/boostcampwm2023/web11-SSOCK/assets/98443541/f20d4c20-2ae9-4415-bf74-83adee7ac27a)

그림과 같이 유리 구슬 내부의 모델 선택시 Tree의 이벤트 함수가 2번 또는 3번씩 실행되는 경우가 생김

또 아래 사진 경우와 같이 모델이 보이지 않는 시야에서 클릭시에도 이벤트가 발생됨
여러 장식품이 겹쳐져 있는 경우 클릭시 문제가 생길것이 예상됨

![스크린샷 2023-11-10 005856](https://github.com/boostcampwm2023/web11-SSOCK/assets/98443541/f62f875a-112f-419e-9492-c59c3d7aa946)

## ❗ 문제 해결
- [ ] 유리 내부 장식품 클릭시 함수가 여러번 실행
- [ ] 안보이는 시야에서도 클릭 이벤트 발생

**Comment by 5nxtnxtnxt** [comment]
- 유리 내부 장식품 클릭시 함수가 여러번 실행
  - Tree에서만 발생
    - 이건 tree model이 하나의 object가 아니라 기둥, 나무, 장식, 별 따로 불러와져서 그럼
    - blender에서 export할때 join해서 하나의 object로 내보내면 됨
    - == 다른 이벤트를 가져야하는 object는 반대로 다른 object로 내보내도록 해야함 
    
- 안보이는 시야에서도 클릭 이벤트 발생 
  - raycaster 의 layer 사용하면 해당 layer에 속하는 object만 판단 하는 것 같은데 이거 사용해보면 될 것같음
    - 참고 : https://threejs.org/docs/?q=rayc#api/en/core/Raycaster
