### ISSUE TITLE
[FE] 캔버스 위 UI 클릭 후 렌더링 방법

### ISSUE THREAD

**Issue by esthel7** [boostcampwm2023/web11-SSOCK#21]
## 💦 이슈 설명
- 메인 화면에서 버튼 누르면 캔버스는 렌더링하지 않고 UI 부분만 렌더링 필요 ➡️ 불필요한 렌더링 방지

|before click|after click|
|--|--|
|![image](https://github.com/boostcampwm2023/web11-SSOCK/assets/96722691/7a708f60-c9ed-4a76-beda-e840f19d2ede)|![image](https://github.com/boostcampwm2023/web11-SSOCK/assets/96722691/3d30d6f6-d2fa-4d3b-b18c-ed9e97de531d)|

## ❗ 문제 해결
- [x] useState를 최소한의 단위에서 수행
  - `App.tsx`에는 렌더링이 최소화되도록 유지 ➡️ 컴포넌트화하여 useState 위치 신경쓰기❗

**Comment by 5nxtnxtnxt** [comment]
APP <- 여기서 useState를 가지고있어서 변경될때 Canvas까지 reRendering됨
├Canvas 
└UIDiv <- 여기나
&nbsp;&nbsp;└ButtonBox <-여기서 useState를 가져야함 (구조는 확정x)
