### ISSUE TITLE
[FE] 화면별 렌더링 문제

### ISSUE THREAD

**Issue by esthel7** [boostcampwm2023/web11-SSOCK#51]
## 💦 이슈 설명
- 화면별 렌더링 다름 ➡️ 사이트 사이즈가 달라 리렌더링
- `button` 파란색 문제

## ❗ 문제 해결
- `window.innerHeight`?
- `button`에 `color`를 `black`으로 설정

**Comment by kcwww** [comment]
버튼 자체가 파란색인거면 굳이 버튼 태그 말고 div 태그나 a 태그로 이벤트 등록해도 되지 않을까 ?
